<?php
include "point.php";
class MoveAblePoint extends point{
    private $Xspeed;
    private $Yspeed;
    public function __construct($X, $Y,$Xspeed,$Yspeed)
    {
        $this->Xspeed=$Xspeed;
        $this->Yspeed=$Yspeed;
        parent::__construct($X, $Y);
    }

    /**
     * @return mixed
     */
    public function getXspeed()
    {
        return $this->Xspeed;
    }
    public function getX()
    {
        return parent::getX(); // TODO: Change the autogenerated stub
    }
    public function getY()
    {
        return parent::getY(); // TODO: Change the autogenerated stub
    }
    public function getXY()
    {
        return parent::getXY(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getYspeed()
    {
        return $this->Yspeed;
    }
    public function setY($Y)
    {
        parent::setY($Y); // TODO: Change the autogenerated stub
    }
    public function setX($X)
    {
        parent::setX($X); // TODO: Change the autogenerated stub
    }
    public function setXY($X, $Y)
    {
        parent::setXY($X, $Y); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $Xspeed
     */
    public function setXspeed($Xspeed)
    {
        $this->Xspeed = $Xspeed;
    }

    /**
     * @param mixed $Yspeed
     */
    public function setYspeed($Yspeed)
    {
        $this->Yspeed = $Yspeed;
    }
    public function __toString()
    {
        return parent::__toString()."(".$this->Xspeed.",".$this->Yspeed.")"; // TODO: Change the autogenerated stub
    }
    public function setSpeed(){
        $this->Xspeed+=10;
        $this->Yspeed+=10;
    }
    public function getSpeed(){
        $arr=[];
        array_push($arr,$this->Xspeed);
        array_push($arr,$this->Yspeed);
        return $arr;
    }
}