<?php


class MoveAblePoint extends address
{
    private $Speed_X;
    private $Speed_Y;
    public function __construct($X, $Y)
    {
        parent::__construct($X, $Y);
        $this->xSpeed;
        $this->ySpeed;
    }

    /**
     * @param mixed $Speed_X
     */
    public function setSpeedX($Speed_X)
    {
        $this->Speed_X = $Speed_X;
    }

    /**
     * @param mixed $Speed_Y
     */
    public function setSpeedY($Speed_Y)
    {
        $this->Speed_Y = $Speed_Y;
    }

    /**
     * @return mixed
     */
    public function getSpeedX()
    {
        return $this->Speed_X;
    }

    /**
     * @return mixed
     */
    public function getSpeedY()
    {
        return $this->Speed_Y;
    }
    public function SetXY()
    {   $this->xSpeed;
        $this->ySpeed;
        parent::SetXY(); // TODO: Change the autogenerated stub
    }
    public function getPointX()
    {
        return parent::getPointX(); // TODO: Change the autogenerated stub
    }
    public function getPointY()
    {
        return parent::getPointY(); // TODO: Change the autogenerated stub
    }
    public function getArray(): array
    {
        return parent::getArray(); // TODO: Change the autogenerated stub
    }
    public function GetXY()
    {
        return parent::GetXY(); // TODO: Change the autogenerated stub
    }
    public function setPointX($pointX)
    {
        parent::setPointX($pointX); // TODO: Change the autogenerated stub
    }
    public function setPointY($pointY)
    {
        parent::setPointY($pointY); // TODO: Change the autogenerated stub
    }
    public function setArray(array $Array)
    {
        parent::setArray($Array);
        $array=$Array;
        array_push($array,$this->xSpeed);
        array_push($array,$this->ySpeed);
        // TODO: Change the autogenerated stub
    }public function __toString()
{
    return parent::__toString().$this->xSpeed.",".$this->xSpeed; // TODO: Change the autogenerated stub
}
}
$Array=[];
$move= new MoveAblePoint();
$move->setPointX(10);
$move->setPointY(20);
$move->setSpeedX(5);
$move->setSpeedY(5);
$move->setArray($Array);
echo "hello";